### ISSUE TITLE
pre-commit & 이슈 템플릿 & PR 템플릿 설정하기 

### ISSUE THREAD

**Issue by pykido** [GongMolCamp/DogNoThreeBE#12]
## 📝 이슈 설명

pre-commit 적용 후 이슈 템플릿, PR 템플릿을 설정합니다. 

### 1. pre-commit 
코드 커밋 시 자동으로 특정 작업을 실행해주는 pre-commit hook을 설정합니다. 이를 통해 코드 품질을 유지하고 일관성을 확보하고자 합니다.

### 2. Issue template 
팀프로젝트를 하며 작업들을 효율적으로 관리하기 위해 이슈 템플릿을 사용하고자 합니다! 
issue 등록시 assignees, labels, projects 설정 후 설명과 TODO 리스트를 게시해주시기 바랍니다. 

### 3. PR template 
issue template과 마찬가지로 작업의 효율성을 위해 PR 템플릿을 사용하고자 합니다!
PR 등록시 assignees, reviewers, 리뷰 요청사항 등을 꼭 포함하여 게시해주시기 바랍니다.

## ☑️ TODO

- [x] pre-commit 설정
- [x] issue template 설정
- [x] PR 템플릿 설정
