### ISSUE TITLE
2️⃣ 뉴스 데이터 가공 

### ISSUE THREAD

**Issue by pykido** [GongMolCamp/DogNoThreeBE#17]
## 📝 이슈 설명

뉴스 데이터를 가공합니다. 

## ☑️ TODO
- [x] chatgpt api 불러오기 
- [x] #22
- [x] Gpt 응답을 repository 및 mysql db를 활용해서 데이터베이스에 저장하기 
- [x] openai playground에서 프롬프트 엔지니어링 수행 
- [x] Fine-tuning 수행
